# 빌드 단계
FROM gradle:8.7.0-jdk21 AS builder

# Railway 환경변수를 빌드 타임에 ARG로 선언
ARG SUPABASE_URL
ARG SUPABASE_USERNAME
ARG SUPABASE_PASSWORD
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION
ARG AWS_BUCKET_NAME
ARG OAuth_GOOGLE_CLIENT_ID
ARG OAuth_GOOGLE_CLIENT_SECRET
ARG OAuth_GOOGLE_SCOPE
ARG OAuth_GOOGLE_REDIRECT_URI
ARG KAKAO_RESTAPI_KEY

# 빌드 시 환경변수로도 주입 (Spring Boot가 필요 시 사용할 수 있도록)
ENV SUPABASE_URL=$SUPABASE_URL \
    SUPABASE_USERNAME=$SUPABASE_USERNAME \
    SUPABASE_PASSWORD=$SUPABASE_PASSWORD \
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    AWS_REGION=$AWS_REGION \
    AWS_BUCKET_NAME=$AWS_BUCKET_NAME \
    OAuth_GOOGLE_CLIENT_ID=$OAuth_GOOGLE_CLIENT_ID \
    OAuth_GOOGLE_CLIENT_SECRET=$OAuth_GOOGLE_CLIENT_SECRET \
    OAuth_GOOGLE_SCOPE=$OAuth_GOOGLE_SCOPE \
    OAuth_GOOGLE_REDIRECT_URI=$OAuth_GOOGLE_REDIRECT_URI \
    KAKAO_RESTAPI_KEY=$KAKAO_RESTAPI_KEY

WORKDIR /app
COPY . .
RUN ./gradlew clean build -x test -x check

# 런타임 단계
FROM eclipse-temurin:21-jdk

# 위에서 받은 환경변수들을 런타임에도 전달
ARG SUPABASE_URL
ARG SUPABASE_USERNAME
ARG SUPABASE_PASSWORD
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION
ARG AWS_BUCKET_NAME
ARG OAuth_GOOGLE_CLIENT_ID
ARG OAuth_GOOGLE_CLIENT_SECRET
ARG OAuth_GOOGLE_SCOPE
ARG OAuth_GOOGLE_REDIRECT_URI
ARG KAKAO_RESTAPI_KEY

ENV SUPABASE_URL=$SUPABASE_URL \
    SUPABASE_USERNAME=$SUPABASE_USERNAME \
    SUPABASE_PASSWORD=$SUPABASE_PASSWORD \
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    AWS_REGION=$AWS_REGION \
    AWS_BUCKET_NAME=$AWS_BUCKET_NAME \
    OAuth_GOOGLE_CLIENT_ID=$OAuth_GOOGLE_CLIENT_ID \
    OAuth_GOOGLE_CLIENT_SECRET=$OAuth_GOOGLE_CLIENT_SECRET \
    OAuth_GOOGLE_SCOPE=$OAuth_GOOGLE_SCOPE \
    OAuth_GOOGLE_REDIRECT_URI=$OAuth_GOOGLE_REDIRECT_URI \
    KAKAO_RESTAPI_KEY=$KAKAO_RESTAPI_KEY

WORKDIR /app
COPY --from=builder /app/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["sh", "-c", "env && java -Xmx768m -Xms384m -jar app.jar"]